use northwind;
-- 1. 29
SELECT *
FROM SUPPLIERS;

-- 2. 20362.93
SELECT SUM(SALARY) AS TOTAL
FROM EMPLOYEES;

-- 3. 2.5000
SELECT MIN(UNITPRICE) AS CHEAPEST
FROM PRODUCTS;

-- 4. 28.87
SELECT AVG(UNITPRICE) AS AVERAGECOST
FROM PRODUCTS;

-- 5. 263.5000
SELECT MAX(UNITPRICE) AS CHEAPEST
FROM PRODUCTS;

-- 6.
SELECT SUPPLIERID, PRODUCTNAME, UNITSONORDER
FROM PRODUCTS;

-- 7.
SELECT CATEGORYID, AVG(UNITPRICE) AS AVGPRICE
FROM PRODUCTS
group by CATEGORYID;

-- 8. 
SELECT SUPPLIERID, UNITSONORDER
FROM PRODUCTS
WHERE UNITSONORDER >= 5;

-- 9. 
SELECT PRODUCTID, PRODUCTNAME, UNITPRICE * UNITSINSTOCK AS VALUE
FROM PRODUCTS
ORDER BY VALUE DESC, PRODUCTNAME ASC ;